apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-orders
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: retail-store
  source:
    repoURL: https://github.com/CloudOps2029/EKS-AUTOMODE--Retail-Application-Project-with-ARGOCD-GitOps-Approach-
    targetRevision: main
    path: src/orders/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
